# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the contents of the specified directory into the container at /usr/src/app
COPY C:\\Users\\dysco\\OneDrive\\Desktop\\STOCKBOT .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run buysignals.py when the container launches
CMD ["python", "buysignals.py"]

#STOCKBOT. Made by Dylan Hoag

