name: Create database backups on a CRON Schedule

on:
  schedule:
    - cron: "00 8 * * *"

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a database dump
        run: mysqldump --no-tablespaces --column-statistics=0h ${{ secrets.HOST }} -u ${{ secrets.USERNAME }} -p${{ secrets.PASSWORD }} ${{ secrets.DB_NAME }} > backup.sql

      - name: Commit database dumps
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -am "Automated database dump"
          git push
