name: Run Daily Scripts

on:
  schedule:
    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install scipy
          pip install yfinance
          # Add any other dependency installation commands here if needed

      - name: Run buysignals.py
        run: python buysignals.py

      - name: Run sellsignals.py
        run: python sellsignals.py








